// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// `dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// `
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABmzbTBQjIeu1SR_jcmEh2DU7tSCxyJ8s',
    appId: '1:927342164821:web:ede3986ea154d9f972cddc',
    messagingSenderId: '927342164821',
    projectId: 'fileuploader-90aee',
    authDomain: 'fileuploader-90aee.firebaseapp.com',
    storageBucket: 'fileuploader-90aee.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABmzbTBQjIeu1SR_jcmEh2DU7tSCxyJ8s',
    appId: '1:927342164821:android:ede3986ea154d9f972cddc',
    messagingSenderId: '927342164821',
    projectId: 'fileuploader-90aee',
    storageBucket: 'fileuploader-90aee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABmzbTBQjIeu1SR_jcmEh2DU7tSCxyJ8s',
    appId: '1:927342164821:ios:ede3986ea154d9f972cddc',
    messagingSenderId: '927342164821',
    projectId: 'fileuploader-90aee',
    storageBucket: 'fileuploader-90aee.firebasestorage.app',
    iosBundleId: 'com.example.melodyHub',
  );
}
